### ISSUE TITLE
[Feature] Support arbitrary parameter for SQL INSERT statement for jdbc_out

### ISSUE THREAD

**Issue by hkkenneth** [KHP-Informatics/turbo-laser#14]
Currently the parameter template is supported by `BeanPropertyItemSqlParameterSourceProvider`. Sometimes we want to write something other than `Document` object's bean property to the database.

Most information generated by the pipeline is stored at `Document`'s `HashMap<String,Object> associativeArray`. Being able to use SQL parameter from this map would be great.

**Comment by afolarin** [comment]
This issue was moved to CogStack/cogstack#24
