### ISSUE TITLE
Towards modularity in CogStack for site-specific features

### ISSUE THREAD

**Issue by hkkenneth** [KHP-Informatics/turbo-laser#17]
As CogStack is being deployed at various NHS sites and projects, some site-specific features will be needed. For example, in an UCL project we need to post-process bio-yodie results. In the SLaM timeline project we need to generate thumbnails and PDFs. Both of these are not needed in other CogStack use case.

Goal: new features can be implemented in separate project, loaded dynamically as extra JAR files and configured using properties and profiles.

**Comment by afolarin** [comment]
see example for Signum project https://github.com/KHP-Informatics/cogstack-plugin-signum

**Comment by afolarin** [comment]
This issue was moved to CogStack/cogstack#7
